version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"

# Dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
